"""Add new columns

Revision ID: 06d1d63cb48d
Revises: 7820b20116de
Create Date: 2024-05-15 04:50:08.741658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d1d63cb48d'
down_revision = '7820b20116de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.TEXT(), nullable=True),
    sa.Column('task_description', sa.TEXT(), nullable=True),
    sa.Column('task_date', sa.TIMESTAMP(timezone=True), nullable=True, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_tasks_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('task_status', sa.BOOLEAN(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['training_tasks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_tasks_progress')
    op.drop_table('training_tasks')
    # ### end Alembic commands ###
