"""Add new columns

Revision ID: 1080c4dc7eb5
Revises: 61be8b1a36b6
Create Date: 2024-05-17 08:10:57.825684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1080c4dc7eb5'
down_revision = '61be8b1a36b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sports_name', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_leagues', schema=None) as batch_op:
        batch_op.drop_column('sports_name')

    # ### end Alembic commands ###
