"""Add new columns

Revision ID: 18ba476ec51e
Revises: ddeb7d3b960d
Create Date: 2024-05-15 08:15:26.624880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ba476ec51e'
down_revision = 'ddeb7d3b960d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('oponent', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_schedule')
    # ### end Alembic commands ###
