"""Add new columns

Revision ID: 61be8b1a36b6
Revises: 18ba476ec51e
Create Date: 2024-05-15 08:22:53.347727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61be8b1a36b6'
down_revision = '18ba476ec51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.TEXT(), nullable=True))
        batch_op.drop_column('oponent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oponent', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('opponent')

    # ### end Alembic commands ###
