"""Add all remaining models

Revision ID: bea8c80b256e
Revises: f062ae07e939
Create Date: 2024-04-30 01:12:21.976934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea8c80b256e'
down_revision = 'f062ae07e939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['sport_organizations.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('first_team_id', sa.Integer(), nullable=True),
    sa.Column('second_team_id', sa.Integer(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['sport_leagues.id'], ),
    sa.ForeignKeyConstraint(['second_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['sport_leagues.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['sport_organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_details',
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('start', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('games_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['games_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('games_id')
    )
    op.create_table('game_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('one_point', sa.Integer(), nullable=True),
    sa.Column('two_points', sa.Integer(), nullable=True),
    sa.Column('three_points', sa.Integer(), nullable=True),
    sa.Column('four_points', sa.Integer(), nullable=True),
    sa.Column('five_points', sa.Integer(), nullable=True),
    sa.Column('six_points', sa.Integer(), nullable=True),
    sa.Column('seven_points', sa.Integer(), nullable=True),
    sa.Column('eight_points', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user_profiles.uid'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sport_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_open', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('league_name')
        batch_op.drop_column('league_description')

    with op.batch_alter_table('sport_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('organization_description')
        batch_op.drop_column('organization_name')

    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('sport_name')
        batch_op.drop_column('sport_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sport_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('sport_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('organization_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('sport_leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('league_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_open')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    op.drop_table('game_scores')
    op.drop_table('game_details')
    op.drop_table('team_members')
    op.drop_table('games')
    op.drop_table('teams')
    # ### end Alembic commands ###
