"""Update Team Member

Revision ID: cdfde1848d7c
Revises: b0afd6d5dc0f
Create Date: 2024-05-07 08:56:00.387797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfde1848d7c'
down_revision = 'b0afd6d5dc0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('team_members_organization_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_members_league_id_fkey', type_='foreignkey')
        batch_op.drop_column('league_id')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('team_members_league_id_fkey', 'sport_leagues', ['league_id'], ['id'])
        batch_op.create_foreign_key('team_members_organization_id_fkey', 'sport_organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###
