"""Add Athlete Profile

Revision ID: ce9df4fc96b4
Revises:
Create Date: 2024-04-24 11:49:39.358935

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce9df4fc96b4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles_athlete",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("civil_status", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"],
            ["user_profiles.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles_athlete")
    # ### end Alembic commands ###
