"""Add new columns

Revision ID: ddeb7d3b960d
Revises: 568f7666a981
Create Date: 2024-05-15 06:35:34.456984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddeb7d3b960d'
down_revision = '568f7666a981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_tasks_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'team_members', ['team_member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_tasks_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_member_id')

    # ### end Alembic commands ###
