"""Add new columns

Revision ID: ec0e93db65f9
Revises: 1080c4dc7eb5
Create Date: 2024-05-17 08:37:33.585241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0e93db65f9'
down_revision = '1080c4dc7eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sports_name', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('sports_name')

    # ### end Alembic commands ###
