"""Update Coach Model

Revision ID: ec254ebe7b73
Revises: 25c2479975cb
Create Date: 2024-04-30 14:41:35.907946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec254ebe7b73'
down_revision = '25c2479975cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['sport_leagues.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['sport_organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles_coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('league', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teams', ['team'], ['id'])
        batch_op.create_foreign_key(None, 'sport_leagues', ['league'], ['id'])
        batch_op.drop_column('organization')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles_coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('league')
        batch_op.drop_column('team')

    op.drop_table('team_stats')
    # ### end Alembic commands ###
