"""Add is_owner

Revision ID: edafbd6d3ed3
Revises: cdfde1848d7c
Create Date: 2024-05-07 10:50:37.787596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edafbd6d3ed3'
down_revision = 'cdfde1848d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_column('is_owner')

    # ### end Alembic commands ###
