"""Add additional tables

Revision ID: f062ae07e939
Revises: ce9df4fc96b4
Create Date: 2024-04-24 17:40:13.971290

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f062ae07e939"
down_revision = "ce9df4fc96b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sport_name", sa.TEXT(), nullable=True),
        sa.Column("sport_description", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sport_leagues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("league_name", sa.TEXT(), nullable=True),
        sa.Column("league_description", sa.TEXT(), nullable=True),
        sa.Column("sport_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sport_organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_name", sa.TEXT(), nullable=True),
        sa.Column("organization_description", sa.TEXT(), nullable=True),
        sa.Column("sport_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_profiles_coach",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"],
            ["user_profiles.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles_coach")
    op.drop_table("sport_organizations")
    op.drop_table("sport_leagues")
    op.drop_table("sports")
    # ### end Alembic commands ###
